# Generated by Django 6.1.1 on 2026-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Tentatives')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Consommé le')),
            ],
            options={
                'verbose_name': 'Code de vérification e-mail',
                'verbose_name_plural': 'Codes de vérification e-mail',
                'ordering': ('-created_at',),
            },
        ),
    ]
