# Generated by Django 6.1.1 on 2026-09-23 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nni', models.CharField(db_index=True, max_length=32, unique=True, verbose_name="Numéro National d'Identification (NNI)")),
                ('inam', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name="Numéro d'Assuré INAM")),
                ('numero_carte', models.CharField(blank=True, default='', max_length=32, verbose_name="N° de carte d'assuré")),
                ('numero_feuille', models.CharField(blank=True, default='', max_length=64, verbose_name='N° de feuille de soins')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom')),
                ('nom_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom (arabe)')),
                ('prenom_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom (arabe)')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, default='', max_length=100, verbose_name='Lieu de naissance')),
                ('telephone', models.CharField(blank=True, default='', max_length=32, verbose_name='Téléphone portable')),
                ('centre_hospitalier', models.CharField(blank=True, default='', max_length=160, verbose_name='Centre hospitalier')),
                ('photo', models.BinaryField(blank=True, null=True, verbose_name='Photo (bytea)')),
                ('photo_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Type MIME de la photo')),
                ('photo_nom', models.CharField(blank=True, default='', max_length=160, verbose_name='Nom du fichier photo')),
                ('photo_path', models.CharField(blank=True, default='', max_length=255, verbose_name='Chemin de la photo')),
                ('code_qr', models.TextField(blank=True, default='', help_text="Laisser vide pour générer automatiquement le code à partir de l'assuré.", verbose_name='Contenu du code QR')),
            ],
            options={
                'verbose_name': 'Assuré',
                'verbose_name_plural': 'Assurés',
                'db_table': getattr(settings, 'CNAM_ASSURES_TABLE', 'assures'),
                'ordering': ('nom', 'prenom', 'nni'),
            },
        ),
    ]
