# Generated by Django 6.1.1 on 2026-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0002_assure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, unique=True, verbose_name="Nom de l'établissement")),
                ('type_etablissement', models.CharField(choices=[('HOPITAL', 'Hôpital'), ('CLINIQUE', 'Clinique'), ('CENTRE_SANTE', 'Centre de santé'), ('CENTRE_MEDICAL', 'Centre médical'), ('DISPENSAIRE', 'Dispensaire')], default='CENTRE_SANTE', max_length=32, verbose_name="Type d'établissement")),
                ('ville', models.CharField(blank=True, default='', max_length=100, verbose_name='Ville')),
                ('adresse', models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, default='', max_length=32, verbose_name='Téléphone')),
                ('conventionne', models.BooleanField(default=True, verbose_name='Conventionné CNAM')),
            ],
            options={
                'verbose_name': 'Établissement de santé',
                'verbose_name_plural': 'Établissements de santé',
                'db_table': 'etablissements',
                'ordering': ('nom', 'ville'),
            },
        ),
    ]
