# Generated by Django 6.1.1 on 2026-09-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0004_etablissements_conventionnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='specialite',
            field=models.CharField(blank=True, default='', help_text='Texte affiché après le nom, ex : « Hôpital général et urgences ».', max_length=160, verbose_name='Spécialités / activités'),
        ),
    ]
